#!/bin/bash
# Auto-generated deployment script for staging repository
# Generated by Repository Switcher

set -e

echo "🚀 DEPLOYING TO STAGING REPOSITORY"
echo "Target: Private staging repository - full codebase"
echo "Remote: staging (https://github.com/wmoore012/staging_yt_analytics.git)"

# Switch repository target
python scripts/repo_switcher.py switch staging

# Check git status
echo "📊 Checking git status..."
git status

# Add files (respecting exclusion rules)
echo "📁 Adding files..."
git add .

# Show what will be committed
echo "📋 Files to be committed:"
git diff --cached --name-only

# Commit with timestamp
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
git commit -m "deploy: Deploy to staging repository at $TIMESTAMP

🎯 Deployment Target: staging
📁 Repository: Private staging repository - full codebase
🔗 Remote: staging
⏰ Timestamp: $TIMESTAMP

Built with Grammy-nominated producer + M.S. Data Science standards 🎵📊"

# Push to target repository
echo "🚀 Pushing to staging..."
git push staging main

echo "✅ Successfully deployed to staging repository!"
