"""
Tests for auto-generated summary system.
Implements TDD approach for pattern detection and intelligent summary generation.
"""

from typing import Any, Dict, List
from unittest.mock import MagicMock, patch

import numpy as np
import pandas as pd
import pytest


class TestAutoGeneratedSummarySystem:

    @pytest.fixture
    def sample_analytics_data(self):
        """Create comprehensive analytics data for summary testing."""
        from src.youtubeviz.config_validation import get_artists_from_env

        artists, _ = get_artists_from_env()

        # Performance data with clear patterns
        performance_data = []
        for i, artist in enumerate(artists):
            # Create different performance patterns for each artist
            base_views = [50000, 75000, 100000, 25000, 150000, 80000][i]  # Different performance levels

            for day in range(30):
                # Add some artists with growth trends, others declining
                if artist == "Flyana Boss":
                    trend_multiplier = 1 + (day * 0.05)  # Strong growth
                elif artist == "BiC Fizzle":
                    trend_multiplier = 1 + (day * 0.02)  # Moderate growth
                elif artist == "re6ce":
                    trend_multiplier = 1 - (day * 0.01)  # Slight decline
                else:
                    trend_multiplier = 1 + np.random.uniform(-0.1, 0.1)  # Stable

                views = int(base_views * trend_multiplier * np.random.uniform(0.8, 1.2))

                performance_data.append(
                    {
                        "artist_name": artist,
                        "date": pd.Timestamp.now() - pd.Timedelta(days=30 - day),
                        "views": views,
                        "likes": int(views * np.random.uniform(0.03, 0.07)),
                        "comments": int(views * np.random.uniform(0.005, 0.015)),
                        "engagement_rate": np.random.uniform(3, 8),
                    }
                )

        # Sentiment data with patterns
        sentiment_data = []
        sentiment_patterns = {
            "Flyana Boss": {"positive": 0.8, "negative": 0.1, "neutral": 0.1},  # Very positive
            "COBRAH": {"positive": 0.7, "negative": 0.2, "neutral": 0.1},  # Mostly positive
            "BiC Fizzle": {"positive": 0.6, "negative": 0.3, "neutral": 0.1},  # Mixed
            "Raiche": {"positive": 0.65, "negative": 0.25, "neutral": 0.1},  # Good
            "Corook": {"positive": 0.75, "negative": 0.15, "neutral": 0.1},  # Very good
            "re6ce": {"positive": 0.5, "negative": 0.4, "neutral": 0.1},  # Polarizing
        }

        for artist in artists:
            pattern = sentiment_patterns[artist]
            for i in range(50):
                sentiment = np.random.choice(
                    ["positive", "negative", "neutral"],
                    p=[pattern["positive"], pattern["negative"], pattern["neutral"]],
                )
                sentiment_data.append(
                    {
                        "artist_name": artist,
                        "sentiment": sentiment,
                        "comment": f"Sample comment {i} for {artist}",
                        "sentiment_score": np.random.uniform(-1, 1),
                    }
                )

        return {"performance": pd.DataFrame(performance_data), "sentiment": pd.DataFrame(sentiment_data)}

    def test_pattern_detection_triggers_summary_generation(self, sample_analytics_data):
        """Test that system detects patterns in data that trigger summary generation."""
        from youtubeviz.summary_generator import detect_performance_patterns

        patterns = detect_performance_patterns(sample_analytics_data["performance"])

        # Should detect different types of patterns
        assert "growth_artists" in patterns, "Should detect artists with growth patterns"
        assert "declining_artists" in patterns, "Should detect artists with declining performance"
        assert "top_performers" in patterns, "Should detect top performing artists"
        assert "engagement_leaders" in patterns, "Should detect engagement leaders"

        # Should have specific artists in appropriate categories
        assert len(patterns["growth_artists"]) > 0, "Should identify growth artists"
        assert len(patterns["top_performers"]) > 0, "Should identify top performers"

    def test_global_variable_exposure_from_env_config(self, sample_analytics_data):
        """Test that summary system exposes global variables from .env configuration."""
        from youtubeviz.summary_generator import get_summary_config

        config = get_summary_config()

        # Should expose configurable parameters
        assert "growth_threshold" in config, "Should expose growth threshold setting"
        assert "sentiment_threshold" in config, "Should expose sentiment threshold setting"
        assert "top_performer_percentile" in config, "Should expose top performer percentile"
        assert "summary_tone" in config, "Should expose summary tone setting"

        # Should be tunable from environment
        assert isinstance(config["growth_threshold"], (int, float)), "Growth threshold should be numeric"
        assert config["sentiment_threshold"] >= 0, "Sentiment threshold should be non-negative"

    def test_automatic_markdown_summary_creation(self, sample_analytics_data):
        """Test automatic markdown summary creation based on chart insights."""
        from youtubeviz.summary_generator import generate_markdown_summary

        summary = generate_markdown_summary(
            performance_data=sample_analytics_data["performance"], sentiment_data=sample_analytics_data["sentiment"]
        )

        # Should generate proper markdown format
        assert isinstance(summary, str), "Summary should be a string"
        assert "# " in summary or "## " in summary, "Summary should have markdown headers"
        assert "- " in summary or "* " in summary, "Summary should have bullet points"

        # Should include key insights
        assert "artist" in summary.lower(), "Summary should mention artists"
        assert "performance" in summary.lower() or "views" in summary.lower(), "Summary should mention performance"
        assert "sentiment" in summary.lower() or "fan" in summary.lower(), "Summary should mention sentiment"

        # Should be substantial content
        assert len(summary) > 200, "Summary should be substantial (>200 characters)"

    def test_summary_includes_hard_truths_with_compassionate_recommendations(self, sample_analytics_data):
        """Test that summary includes honest facts with compassionate recommendations."""
        from youtubeviz.summary_generator import generate_compassionate_insights

        insights = generate_compassionate_insights(
            performance_data=sample_analytics_data["performance"], sentiment_data=sample_analytics_data["sentiment"]
        )

        # Should have both hard truths and recommendations
        assert "hard_truths" in insights, "Should include hard truths section"
        assert "recommendations" in insights, "Should include recommendations section"
        assert "opportunities" in insights, "Should include opportunities section"

        # Hard truths should be honest but respectful
        hard_truths = insights["hard_truths"]
        assert len(hard_truths) > 0, "Should have at least one hard truth"
        for truth in hard_truths:
            assert isinstance(truth, str), "Each hard truth should be a string"
            assert len(truth) > 20, "Hard truths should be substantial"

        # Recommendations should be actionable and compassionate
        recommendations = insights["recommendations"]
        assert len(recommendations) > 0, "Should have at least one recommendation"
        for rec in recommendations:
            assert isinstance(rec, str), "Each recommendation should be a string"
            # Check if recommendation contains supportive language
            supportive_words = [
                "help",
                "support",
                "improve",
                "focus",
                "consider",
                "remember",
                "use",
                "understand",
                "maintain",
                "try",
                "experiment",
                "expand",
            ]
            has_supportive_word = any(word in rec.lower() for word in supportive_words)
            assert has_supportive_word, f"Recommendation should be supportive: '{rec}'"

    def test_summary_integration_with_main_notebook_workflow(self, sample_analytics_data):
        """Test that summary integrates seamlessly with main notebook workflow."""
        from youtubeviz.summary_generator import create_notebook_summary_section

        # Should create a complete notebook section
        summary_section = create_notebook_summary_section(
            performance_data=sample_analytics_data["performance"], sentiment_data=sample_analytics_data["sentiment"]
        )

        # Should return notebook-ready content
        assert "markdown_content" in summary_section, "Should include markdown content"
        assert "key_metrics" in summary_section, "Should include key metrics"
        assert "action_items" in summary_section, "Should include action items"

        # Markdown content should be notebook-ready
        markdown = summary_section["markdown_content"]
        assert "# " in markdown or "## " in markdown, "Should have proper headers"
        assert len(markdown.split("\n")) > 5, "Should have multiple lines"

        # Key metrics should be quantified
        metrics = summary_section["key_metrics"]
        assert len(metrics) > 0, "Should have key metrics"
        for metric in metrics:
            assert "value" in metric, "Each metric should have a value"
            assert "description" in metric, "Each metric should have a description"

    def test_pattern_detection_with_different_data_scenarios(self):
        """Test pattern detection with various data scenarios."""
        from youtubeviz.summary_generator import detect_performance_patterns

        # Test with all growth scenario
        growth_data = pd.DataFrame(
            {
                "artist_name": ["Artist A", "Artist B"] * 10,
                "date": pd.date_range("2024-01-01", periods=20, freq="D"),
                "views": [1000 + i * 100 for i in range(20)],  # Steady growth
                "engagement_rate": [5.0] * 20,
            }
        )

        growth_patterns = detect_performance_patterns(growth_data)
        assert len(growth_patterns["growth_artists"]) > 0, "Should detect growth in growth scenario"

        # Test with all decline scenario
        decline_data = pd.DataFrame(
            {
                "artist_name": ["Artist C", "Artist D"] * 10,
                "date": pd.date_range("2024-01-01", periods=20, freq="D"),
                "views": [2000 - i * 50 for i in range(20)],  # Steady decline
                "engagement_rate": [3.0] * 20,
            }
        )

        decline_patterns = detect_performance_patterns(decline_data)
        assert len(decline_patterns["declining_artists"]) > 0, "Should detect decline in decline scenario"

    def test_summary_configuration_from_environment_variables(self):
        """Test that summary system reads configuration from environment variables."""
        from youtubeviz.summary_generator import get_summary_config

        # Test with mock environment variables
        with patch.dict(
            "os.environ",
            {
                "SUMMARY_GROWTH_THRESHOLD": "0.15",
                "SUMMARY_SENTIMENT_THRESHOLD": "0.7",
                "SUMMARY_TOP_PERFORMER_PERCENTILE": "80",
                "SUMMARY_TONE": "compassionate",
            },
        ):
            config = get_summary_config()

            assert config["growth_threshold"] == 0.15, "Should read growth threshold from env"
            assert config["sentiment_threshold"] == 0.7, "Should read sentiment threshold from env"
            assert config["top_performer_percentile"] == 80, "Should read percentile from env"
            assert config["summary_tone"] == "compassionate", "Should read tone from env"

    def test_summary_handles_edge_cases_gracefully(self):
        """Test that summary system handles edge cases gracefully."""
        from youtubeviz.summary_generator import generate_markdown_summary

        # Test with empty data
        empty_performance = pd.DataFrame(columns=["artist_name", "views", "date"])
        empty_sentiment = pd.DataFrame(columns=["artist_name", "sentiment"])

        empty_summary = generate_markdown_summary(empty_performance, empty_sentiment)
        assert isinstance(empty_summary, str), "Should return string even with empty data"
        assert len(empty_summary) > 0, "Should return non-empty summary even with no data"
        assert (
            "no performance or sentiment data" in empty_summary.lower() or "insufficient" in empty_summary.lower()
        ), "Should indicate data limitations"

        # Test with single artist
        single_artist_data = pd.DataFrame(
            {
                "artist_name": ["Solo Artist"] * 5,
                "views": [1000, 1100, 1200, 1300, 1400],
                "date": pd.date_range("2024-01-01", periods=5, freq="D"),
                "engagement_rate": [5.0] * 5,
            }
        )

        single_sentiment = pd.DataFrame(
            {"artist_name": ["Solo Artist"] * 10, "sentiment": ["positive"] * 8 + ["negative"] * 2}
        )

        single_summary = generate_markdown_summary(single_artist_data, single_sentiment)
        assert "Solo Artist" in single_summary, "Should handle single artist data"

    def test_summary_performance_and_efficiency(self, sample_analytics_data):
        """Test that summary generation is performant and efficient."""
        import time

        from youtubeviz.summary_generator import generate_markdown_summary

        # Test execution time
        start_time = time.time()

        summary = generate_markdown_summary(
            performance_data=sample_analytics_data["performance"], sentiment_data=sample_analytics_data["sentiment"]
        )

        execution_time = time.time() - start_time

        # Should execute quickly (under 2 seconds for summary generation)
        assert execution_time < 2.0, f"Summary generation took too long: {execution_time:.2f}s"
        assert len(summary) > 100, "Should generate substantial summary quickly"


if __name__ == "__main__":
    pytest.main([__file__])
